

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Validate and Compile with Maven
        run: docker ps
